// Options par défaut réutilisables pour les leads
// Sources, secteurs (listes) ; domaines = saisie libre par la commerciale

export const DEFAULT_LEAD_SOURCES = [
  "Non renseigné",
  "Facebook",
  "WhatsApp",
  "LinkedIn",
  "Site web",
  "Bouche-à-oreille",
  "Email",
  "Partenaires",
  "Salon / évènement",
  "Recommandation client",
  "Appel entrant",
  "Prospection terrain",
  "Autre",
] as const;

export const DEFAULT_ACTIVITY_SECTORS = [
  "Activités juridiques et comptables",
  "Agriculture et élevage",
  "Architecture, études et normes",
  "Artisanat d'art, audiovisuel et spectacle",
  "Automobile",
  "Bâtiment et travaux publics (BTP)",
  "Commerce et distribution",
  "Communication et marketing",
  "Culture et patrimoine",
  "Enseignement et formation",
  "Environnement",
  "Finance, banque et assurance",
  "Gestion administrative et ressources humaines",
  "Hôtellerie et restauration",
  "Immobilier",
  "Industrie - Alimentaire",
  "Industrie - Bois",
  "Industrie - Chimie",
  "Industrie - Métallurgie",
  "Industrie - Papier et imprimerie",
  "Industrie - Textile et mode",
  "Industrie - Électronique",
  "Industries",
  "Informatique et télécommunication",
  "Logistique et transport",
  "Maintenance, entretien et nettoyage",
  "Recherche",
  "Santé",
  "Service public, défense et sécurité",
  "Service à la personne",
  "Social",
  "Sport, animation et loisir",
  "Tourisme",
  "Édition",
  "Énergie",
  "Autre",
] as const;

export const DEFAULT_CIVILITIES = [
  "M.",
  "Mme",
  "Mlle",
  "Dr",
  "Pr",
] as const;

