-- CreateEnum
CREATE TYPE "LeadTypeClient" AS ENUM ('COLLECTIVITE_TERRITORIALE', 'PARTICULIER_B2C', 'ENTREPRISE_PRIVEE_B2B', 'GOUVERNEMENT_SECTEUR_PUBLIC', 'HOTELS_ET_ESPACES_EVENEMENTIEL', 'INSTITUTION_MULTILATERALE_OI', 'AGENCE_DE_COOPERATION_OPERATEUR', 'INSTITUTION_FINANCIERE_INTERNATIONALE_IFI', 'ONG_ASSOCIATION_ACADEMIQUE', 'NON_DETERMINE');

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "leadType" "LeadTypeClient" NOT NULL DEFAULT 'NON_DETERMINE';
